# Provide a custom message
message: ""

# Remember to set service.type=ClusterIP if you are using an ingress
ingress:
  configured: false
  rewritePath: true
  pathPrefix: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  externalIPs: 192.168.49.3

deployment:
  replicaCount: 2
  container:
    image:
      repository: "alupuleasa/hello-world"
      tag: "v1.0.0" # uses chart appVersion if not provided
      pullPolicy: IfNotPresent
    port: 80

  # Currently only linux images on amd64 architecture are supported - support for arm64 and windows/amd64 coming ...
  nodeSelector:
    kubernetes.io/os: linux
    kubernetes.io/arch: amd64

  resources: {}

  tolerations: []

  affinity: {}

